@echo off
setlocal EnableExtensions DisableDelayedExpansion

set "PROJECT_ROOT=%~1"
set "CONFIG_FILE=%~2"
set "UV_INSTALL_URL=https://astral.sh/uv/install.ps1"

if not defined PROJECT_ROOT (
    echo ERROR: Project root argument is missing. This shared launcher must be called by a project launcher.
    call :Pause
    exit /b 1
)
if not defined CONFIG_FILE (
    echo ERROR: Launch config argument is missing. This shared launcher must be called by a project launcher.
    call :Pause
    exit /b 1
)

if not exist "%PROJECT_ROOT%\." (
    echo ERROR: Project root directory does not exist or is not accessible:
    echo   %PROJECT_ROOT%
    call :Pause
    exit /b 1
)
for %%I in ("%PROJECT_ROOT%") do set "PROJECT_ROOT=%%~fI"

if not exist "%CONFIG_FILE%" (
    echo ERROR: Launch config does not exist:
    echo   %CONFIG_FILE%
    call :Pause
    exit /b 1
)
for %%F in ("%CONFIG_FILE%") do if %%~zF EQU 0 (
    echo ERROR: Launch config is empty:
    echo   %CONFIG_FILE%
    call :Pause
    exit /b 1
)

where powershell.exe >nul 2>&1
if errorlevel 1 (
    echo ERROR: Windows PowerShell was not found.
    echo Windows PowerShell is required to read launch_config.ini and install uv when needed.
    call :Pause
    exit /b 1
)

set "NATIVE_ARCH=%PROCESSOR_ARCHITECTURE%"
if defined PROCESSOR_ARCHITEW6432 set "NATIVE_ARCH=%PROCESSOR_ARCHITEW6432%"
if /I "%NATIVE_ARCH%"=="AMD64" (
    echo Detected Windows on x86_64 ^(AMD64^).
) else if /I "%NATIVE_ARCH%"=="ARM64" (
    echo Detected Windows on ARM64.
) else if /I "%NATIVE_ARCH%"=="x86" (
    echo WARNING: Detected 32-bit Windows/x86 process architecture.
    echo WARNING: uv support is best-effort on Windows i686; x86_64 or ARM64 Windows is recommended.
) else (
    echo WARNING: Unrecognized Windows architecture: %NATIVE_ARCH%
)

call :ReadLaunchConfig source_dir SOURCE_DIR_VALUE
if errorlevel 1 goto :ConfigReadFailed
call :ReadLaunchConfig launch_file LAUNCH_FILE_VALUE
if errorlevel 1 goto :ConfigReadFailed
call :ReadLaunchConfig ensure_user_dir ENSURE_USER_DIR
if errorlevel 1 goto :ConfigReadFailed

if not defined SOURCE_DIR_VALUE (
    echo ERROR: source_dir is missing or empty in [Launch] in:
    echo   %CONFIG_FILE%
    call :Pause
    exit /b 1
)
if not defined LAUNCH_FILE_VALUE (
    echo ERROR: launch_file is missing or empty in [Launch] in:
    echo   %CONFIG_FILE%
    call :Pause
    exit /b 1
)

set "SOURCE_DIR_VALUE=%SOURCE_DIR_VALUE:/=\%"
set "LAUNCH_FILE_VALUE=%LAUNCH_FILE_VALUE:/=\%"
set "ENSURE_USER_DIR=%ENSURE_USER_DIR:/=\%"

call :RequireRelativePath "%SOURCE_DIR_VALUE%" source_dir
if errorlevel 1 exit /b 1
call :RequireRelativePath "%LAUNCH_FILE_VALUE%" launch_file
if errorlevel 1 exit /b 1

if /I "%LAUNCH_FILE_VALUE:~-3%"==".py" (
    echo ERROR: launch_file must omit the .py extension.
    echo   Use: %LAUNCH_FILE_VALUE:~0,-3%
    call :Pause
    exit /b 1
)

for %%I in ("%PROJECT_ROOT%\%SOURCE_DIR_VALUE%") do set "SOURCE_DIR=%%~fI"
set "VENV_DIR=%PROJECT_ROOT%\.venv"
set "LAUNCH_PATH=%SOURCE_DIR%\%LAUNCH_FILE_VALUE%.py"

if not exist "%SOURCE_DIR%\." (
    echo ERROR: Configured source_dir does not exist or is not a directory:
    echo   %SOURCE_DIR%
    call :Pause
    exit /b 1
)

if exist "%VENV_DIR%" if not exist "%VENV_DIR%\." (
    echo ERROR: The virtual-environment path exists but is not a directory:
    echo   %VENV_DIR%
    call :Pause
    exit /b 1
)

if not exist "%VENV_DIR%\." (
    call :CheckProjectWritable
    if errorlevel 1 exit /b 1
)

if defined ENSURE_USER_DIR (
    call :EnsureUserDirectory
    if errorlevel 1 exit /b 1
)

call :RequireReadableNonEmptyFile "%SOURCE_DIR%\.python-version" .python-version
if errorlevel 1 exit /b 1
call :RequireReadableNonEmptyFile "%SOURCE_DIR%\pyproject.toml" pyproject.toml
if errorlevel 1 exit /b 1
call :RequireReadableNonEmptyFile "%LAUNCH_PATH%" "Python launch file"
if errorlevel 1 exit /b 1

rem A missing uv.lock is valid on first launch. If one already exists, it
rem must be readable and non-empty; existing lockfiles are never silently
rem replaced or regenerated by the launcher.
if exist "%SOURCE_DIR%\uv.lock" (
    call :RequireReadableNonEmptyFile "%SOURCE_DIR%\uv.lock" uv.lock
    if errorlevel 1 exit /b 1
)

call :ResolveUv
if errorlevel 1 exit /b 1

set "UV_PROJECT_ENVIRONMENT=%VENV_DIR%"

pushd "%SOURCE_DIR%" >nul 2>&1
if errorlevel 1 (
    echo ERROR: Could not change to source_dir:
    echo   %SOURCE_DIR%
    call :Pause
    exit /b 1
)

call :EnsurePython
if errorlevel 1 (
    popd
    exit /b 1
)

if not exist "%SOURCE_DIR%\uv.lock" (
    call :GenerateInitialLockfile
    if errorlevel 1 (
        popd
        exit /b 1
    )
)

echo Synchronizing the project environment from uv.lock...
"%UV_EXE%" sync --locked --no-python-downloads
set "SYNC_STATUS=%ERRORLEVEL%"
if not "%SYNC_STATUS%"=="0" (
    popd
    echo ERROR: uv sync failed with exit code %SYNC_STATUS%.
    echo pyproject.toml and uv.lock may be out of sync, a dependency may not support this Windows/Python architecture,
    echo the network may be unavailable, or the existing .venv may be invalid. See uv's error output above.
    call :Pause
    exit /b %SYNC_STATUS%
)

if not exist "%VENV_DIR%\." (
    popd
    echo ERROR: uv sync completed without creating the expected virtual environment:
    echo   %VENV_DIR%
    call :Pause
    exit /b 1
)

echo Launching: %LAUNCH_FILE_VALUE%.py
"%UV_EXE%" run --locked --no-sync --no-python-downloads python "%LAUNCH_PATH%"
set "LAUNCH_STATUS=%ERRORLEVEL%"
popd

echo.
if "%LAUNCH_STATUS%"=="0" (
    echo Process has ended.
) else (
    echo ERROR: Python launch file exited with code %LAUNCH_STATUS%:
    echo   %LAUNCH_PATH%
)

call :Pause
exit /b %LAUNCH_STATUS%

:ConfigReadFailed
call :Pause
exit /b 1

:GenerateInitialLockfile
echo uv.lock was not found. Generating the initial lockfile...
"%UV_EXE%" lock --no-python-downloads
set "LOCK_STATUS=%ERRORLEVEL%"
if not "%LOCK_STATUS%"=="0" (
    echo ERROR: Failed to generate uv.lock with exit code %LOCK_STATUS%.
    echo Check pyproject.toml, dependency/version compatibility, network access,
    echo and uv's error output above.
    call :Pause
    exit /b %LOCK_STATUS%
)
if not exist "%SOURCE_DIR%\uv.lock" (
    echo ERROR: uv lock completed without creating the expected file:
    echo   %SOURCE_DIR%\uv.lock
    call :Pause
    exit /b 1
)
call :RequireReadableNonEmptyFile "%SOURCE_DIR%\uv.lock" uv.lock
if errorlevel 1 exit /b 1
echo Created initial lockfile:
echo   %SOURCE_DIR%\uv.lock
exit /b 0

:RequireRelativePath
set "CHECK_PATH=%~1"
set "CHECK_LABEL=%~2"
if not defined CHECK_PATH (
    echo ERROR: %CHECK_LABEL% may not be empty.
    call :Pause
    exit /b 1
)
if "%CHECK_PATH:~1,1%"==":" (
    echo ERROR: %CHECK_LABEL% must be a relative path, not a drive-qualified path:
    echo   %CHECK_PATH%
    call :Pause
    exit /b 1
)
if "%CHECK_PATH:~0,1%"=="\" (
    echo ERROR: %CHECK_LABEL% must be a relative path, not a rooted or UNC path:
    echo   %CHECK_PATH%
    call :Pause
    exit /b 1
)
exit /b 0

:RequireReadableNonEmptyFile
set "CHECK_FILE=%~1"
set "CHECK_LABEL=%~2"
if not exist "%CHECK_FILE%" (
    echo ERROR: %CHECK_LABEL% is missing:
    echo   %CHECK_FILE%
    call :Pause
    exit /b 1
)
for %%F in ("%CHECK_FILE%") do if %%~zF EQU 0 (
    echo ERROR: %CHECK_LABEL% is empty:
    echo   %CHECK_FILE%
    call :Pause
    exit /b 1
)
exit /b 0

:ResolveUv
set "UV_EXE="
for /f "usebackq delims=" %%U in (`where uv.exe 2^>nul`) do if not defined UV_EXE set "UV_EXE=%%U"

if defined UV_EXE (
    "%UV_EXE%" --version >nul 2>&1
    if errorlevel 1 (
        echo ERROR: uv was found but could not run successfully:
        echo   %UV_EXE%
        call :Pause
        exit /b 1
    )
    echo Using uv at:
    echo   %UV_EXE%
    "%UV_EXE%" --version
    exit /b 0
)

if not defined LOCALAPPDATA (
    echo ERROR: uv was not found on PATH and LOCALAPPDATA is not set, so the commonUtils uv installation directory cannot be checked.
    call :Pause
    exit /b 1
)

set "UV_INSTALL_DIR=%LOCALAPPDATA%\commonUtils\uv"
set "UV_EXE=%UV_INSTALL_DIR%\uv.exe"

rem uv is intentionally installed without modifying PATH. Check the persistent
rem commonUtils install location before deciding that uv needs to be installed.
if exist "%UV_EXE%" (
    "%UV_EXE%" --version >nul 2>&1
    if errorlevel 1 (
        echo ERROR: uv exists in the commonUtils installation directory but could not run successfully:
        echo   %UV_EXE%
        call :Pause
        exit /b 1
    )
    echo Using uv at:
    echo   %UV_EXE%
    "%UV_EXE%" --version
    exit /b 0
)

set "UV_INSTALLER_FILE=%TEMP%\uv-installer_%RANDOM%_%RANDOM%.ps1"

if not exist "%UV_INSTALL_DIR%\." (
    mkdir "%UV_INSTALL_DIR%" >nul 2>&1
    if errorlevel 1 (
        echo ERROR: Could not create the per-user uv installation directory:
        echo   %UV_INSTALL_DIR%
        call :Pause
        exit /b 1
    )
)

if exist "%UV_INSTALLER_FILE%" del /q "%UV_INSTALLER_FILE%" >nul 2>&1

echo uv was not found. Downloading the official uv installer...
set "UV_DOWNLOAD_TARGET=%UV_INSTALLER_FILE%"
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; try { [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -UseBasicParsing -Uri $env:UV_INSTALL_URL -OutFile $env:UV_DOWNLOAD_TARGET } catch { [Console]::Error.WriteLine($_.Exception.Message); exit 1 }"
if errorlevel 1 (
    if exist "%UV_INSTALLER_FILE%" del /q "%UV_INSTALLER_FILE%" >nul 2>&1
    echo ERROR: Failed to download the uv installer from:
    echo   %UV_INSTALL_URL%
    echo Check the network connection, proxy/firewall settings, and TLS certificates.
    call :Pause
    exit /b 1
)

if not exist "%UV_INSTALLER_FILE%" (
    echo ERROR: The uv installer download reported success, but no installer file was created:
    echo   %UV_INSTALLER_FILE%
    call :Pause
    exit /b 1
)
for %%F in ("%UV_INSTALLER_FILE%") do if %%~zF EQU 0 (
    del /q "%UV_INSTALLER_FILE%" >nul 2>&1
    echo ERROR: The downloaded uv installer is empty.
    call :Pause
    exit /b 1
)

set "UV_NO_MODIFY_PATH=1"
echo Installing uv for the current user into:
echo   %UV_INSTALL_DIR%
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%UV_INSTALLER_FILE%"
set "UV_INSTALL_STATUS=%ERRORLEVEL%"
del /q "%UV_INSTALLER_FILE%" >nul 2>&1
if not "%UV_INSTALL_STATUS%"=="0" (
    echo ERROR: The uv installer returned exit code %UV_INSTALL_STATUS%. uv was not installed successfully.
    call :Pause
    exit /b %UV_INSTALL_STATUS%
)

set "UV_EXE=%UV_INSTALL_DIR%\uv.exe"
if not exist "%UV_EXE%" (
    echo ERROR: uv installation reported success, but uv.exe was not found at the expected location:
    echo   %UV_EXE%
    call :Pause
    exit /b 1
)

"%UV_EXE%" --version >nul 2>&1
if errorlevel 1 (
    echo ERROR: uv.exe was installed but could not run successfully:
    echo   %UV_EXE%
    call :Pause
    exit /b 1
)
echo Using uv at:
echo   %UV_EXE%
"%UV_EXE%" --version
exit /b 0

:CheckProjectWritable
set "WRITE_TEST=%PROJECT_ROOT%\.commonutils_write_test_%RANDOM%_%RANDOM%.tmp"
>"%WRITE_TEST%" echo write-test
if errorlevel 1 (
    echo ERROR: The project root is not writable, so .venv cannot be created there:
    echo   %PROJECT_ROOT%
    call :Pause
    exit /b 1
)
del /q "%WRITE_TEST%" >nul 2>&1
exit /b 0

:EnsureUserDirectory
if not defined USERPROFILE (
    echo ERROR: ensure_user_dir is configured, but USERPROFILE is not set.
    call :Pause
    exit /b 1
)
call :RequireRelativePath "%ENSURE_USER_DIR%" ensure_user_dir
if errorlevel 1 exit /b 1
if "%ENSURE_USER_DIR%"==".." (
    echo ERROR: ensure_user_dir may not escape the current user's home directory.
    call :Pause
    exit /b 1
)
if not "%ENSURE_USER_DIR:..\=%"=="%ENSURE_USER_DIR%" (
    echo ERROR: ensure_user_dir may not contain '..\': %ENSURE_USER_DIR%
    call :Pause
    exit /b 1
)
set "ENSURE_USER_PATH=%USERPROFILE%\%ENSURE_USER_DIR%"
if exist "%ENSURE_USER_PATH%\." exit /b 0

echo Creating user directory:
echo   %ENSURE_USER_PATH%
mkdir "%ENSURE_USER_PATH%" >nul 2>&1
if errorlevel 1 (
    echo ERROR: Could not create configured user directory:
    echo   %ENSURE_USER_PATH%
    call :Pause
    exit /b 1
)
exit /b 0

:EnsurePython
set "PYTHON_REQUEST="
for /f "usebackq tokens=* delims=" %%V in ("%SOURCE_DIR%\.python-version") do (
    if not defined PYTHON_REQUEST set "PYTHON_REQUEST=%%V"
)
if not defined PYTHON_REQUEST (
    echo ERROR: .python-version does not contain a Python version request:
    echo   %SOURCE_DIR%\.python-version
    call :Pause
    exit /b 1
)

echo Requested Python: %PYTHON_REQUEST%
"%UV_EXE%" python find --no-python-downloads >nul 2>&1
if not errorlevel 1 (
    echo A compatible Python installation is already available.
    exit /b 0
)

echo Compatible Python was not found locally. Installing it with uv...
"%UV_EXE%" python install --no-registry
set "PYTHON_INSTALL_STATUS=%ERRORLEVEL%"
if not "%PYTHON_INSTALL_STATUS%"=="0" (
    echo ERROR: Python installation failed with exit code %PYTHON_INSTALL_STATUS% for the request in .python-version:
    echo   %PYTHON_REQUEST%
    echo Check network access, uv output above, available disk space, and whether this Python build exists for this Windows architecture.
    call :Pause
    exit /b %PYTHON_INSTALL_STATUS%
)

"%UV_EXE%" python find --no-python-downloads >nul 2>&1
if errorlevel 1 (
    echo ERROR: uv reported that Python installation completed, but a compatible Python still cannot be resolved for:
    echo   %PYTHON_REQUEST%
    call :Pause
    exit /b 1
)

echo Python installation/resolution succeeded.
exit /b 0

:ReadLaunchConfig
set "CONFIG_KEY=%~1"
set "CONFIG_OUTPUT=%TEMP%\commonutils_launch_%RANDOM%_%RANDOM%.tmp"
if exist "%CONFIG_OUTPUT%" del /q "%CONFIG_OUTPUT%" >nul 2>&1

powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; $path=$env:CONFIG_FILE; $key=$env:CONFIG_KEY; $inLaunch=$false; $values=New-Object System.Collections.Generic.List[string]; foreach($line in [IO.File]::ReadAllLines($path)){ $t=$line.Trim(); if($t -match '^\[(.+)\]$'){ $inLaunch=($matches[1].Trim() -ieq 'Launch'); continue }; if(-not $inLaunch -or $t.Length -eq 0 -or $t.StartsWith('#') -or $t.StartsWith(';')){ continue }; $idx=$line.IndexOf('='); if($idx -lt 0){ continue }; if($line.Substring(0,$idx).Trim() -ieq $key){ $v=$line.Substring($idx+1).Trim(); if($v.Length -ge 2){ if(($v[0] -eq [char]34 -and $v[$v.Length-1] -eq [char]34) -or ($v[0] -eq [char]39 -and $v[$v.Length-1] -eq [char]39)){ $v=$v.Substring(1,$v.Length-2) } }; $values.Add($v) } }; if($values.Count -gt 1){ [Console]::Error.WriteLine(('ERROR: Duplicate ''{0}'' entries were found in [Launch] in {1}.' -f $key,$path)); exit 2 }; if($values.Count -eq 1){ [IO.File]::WriteAllText($env:CONFIG_OUTPUT,$values[0]) } else { [IO.File]::WriteAllText($env:CONFIG_OUTPUT,'') }"
set "READ_STATUS=%ERRORLEVEL%"
if not "%READ_STATUS%"=="0" (
    if exist "%CONFIG_OUTPUT%" del /q "%CONFIG_OUTPUT%" >nul 2>&1
    echo ERROR: Failed to read '%~1' from launch_config.ini.
    exit /b %READ_STATUS%
)

set "%~2="
set /p "%~2="<"%CONFIG_OUTPUT%" 2>nul
if exist "%CONFIG_OUTPUT%" del /q "%CONFIG_OUTPUT%" >nul 2>&1
exit /b 0

:Pause
if not defined COMMONUTILS_NO_PAUSE pause
exit /b 0
